apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-shell
  template:
    metadata:
      labels:
        app: frontend-shell
    spec:
      containers:
        - name: frontend-shell
          image: sladjanapekovic/frontend-shell:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-shell
spec:
  selector:
    app: frontend-shell
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-frontend
  template:
    metadata:
      labels:
        app: books-frontend
    spec:
      containers:
        - name: books-frontend
          image: sladjanapekovic/books-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: books-frontend
spec:
  selector:
    app: books-frontend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-frontend
  template:
    metadata:
      labels:
        app: users-frontend
    spec:
      containers:
        - name: users-frontend
          image: sladjanapekovic/users-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-frontend
spec:
  selector:
    app: users-frontend
  ports:
    - port: 8080
      targetPort: 8080
