apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-gateway
  template:
    metadata:
      labels:
        app: web-gateway
    spec:
      containers:
        - name: web-gateway
          image: sladjanapekovic/web-gateway:latest
          env:
            - name: KNJIGE_SERVICE_URL
              value: http://knjige-service:8000
            - name: IZPOSOJA_SERVICE_URL
              value: http://izposoja-service:8082
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-gateway
spec:
  selector:
    app: web-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-gateway
  template:
    metadata:
      labels:
        app: mobile-gateway
    spec:
      containers:
        - name: mobile-gateway
          image: sladjanapekovic/mobile-gateway:latest
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-gateway
spec:
  selector:
    app: mobile-gateway
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
