apiVersion: apps/v1
kind: Deployment
metadata:
  name: izposoja-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izposoja-postgres
  template:
    metadata:
      labels:
        app: izposoja-postgres
    spec:
      containers:
        - name: izposoja-postgres
          image: bitnami/postgresql:latest
          env:
            - name: POSTGRESQL_USERNAME
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: izposoja_db
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: izposoja-postgres
spec:
  selector:
    app: izposoja-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: izposoja-activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izposoja-activemq
  template:
    metadata:
      labels:
        app: izposoja-activemq
    spec:
      containers:
        - name: izposoja-activemq
          image: symptoma/activemq:latest
          env:
            - name: ACTIVEMQ_ADMIN_LOGIN
              value: admin
            - name: ACTIVEMQ_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 61616
            - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: izposoja-activemq
spec:
  selector:
    app: izposoja-activemq
  ports:
    - name: broker
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: web
      protocol: TCP
      port: 8161
      targetPort: 8161
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: izposoja-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: izposoja-service
  template:
    metadata:
      labels:
        app: izposoja-service
    spec:
      containers:
        - name: izposoja-service
          image: sladjanapekovic/izposoja-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://izposoja-postgres:5432/izposoja_db
            - name: SPRING_R2DBC_USERNAME
              value: postgres
            - name: SPRING_R2DBC_PASSWORD
              value: postgres
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://izposoja-activemq:61616
            - name: SPRING_ACTIVEMQ_USER
              value: admin
            - name: SPRING_ACTIVEMQ_PASSWORD
              value: admin
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: izposoja-service
spec:
  selector:
    app: izposoja-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
