apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabniki-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uporabniki-postgres
  template:
    metadata:
      labels:
        app: uporabniki-postgres
    spec:
      containers:
        - name: uporabniki-postgres
          image: bitnami/postgresql:latest
          env:
            - name: POSTGRESQL_USERNAME
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: uporabniki_db
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: uporabniki-postgres
spec:
  selector:
    app: uporabniki-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uporabniki-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uporabniki-service
  template:
    metadata:
      labels:
        app: uporabniki-service
    spec:
      containers:
        - name: uporabniki-service
          image: sladjanapekovic/uporabniki-service:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: uporabniki-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: uporabniki_db
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: uporabniki-service
spec:
  selector:
    app: uporabniki-service
  ports:
    - port: 50051
      targetPort: 50051
