# trigger docker build
name: Build and publish Docker images

on:
  push:
    branches:
      - main
      - master

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: knjige
            context: ./knjige
            image: knjige-service

          - name: uporabniki
            context: ./uporabniki
            image: uporabniki-service  
            
          - name: izposoja
            context: ./izposoja
            image: izposoja-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/knjige-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/knjige-service:v3
